openapi: 3.0.1
info:
  title: ortelius-ms-textfile-crud
  version: 1.0.0
  description: 'Description to be entered here'
  termsOfService: http://swagger.io/terms/
  contact:
    email: xyz@deployhub.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /
paths:
  "/msapi/textfile":
    get:
      tags:
      - component-textfile-rest
      operationId: getComponentTextfile
      parameters:
      - name: compid
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: filetype
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ComponentTextfile"
    post:
      tags:
      - component-textfile-rest
      operationId: createComponentTextfile
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ComponentTextfile"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ComponentTextfile"
components:
  schemas:
    ComponentTextfile:
      type: object
      properties:
        compid:
          type: integer
          format: int32
        filetype:
          type: string
        file:
          type: array
          items:
            type: string
