replicaCount: 1
image:
  repository: quay.io/ortelius/ms-textfile-crud
  tag: main-v10.0.31-g7178bd
  sha: sha256:832b045115c7ce143cff7a2824edd7bea1f85c9a0cdbc868def14b6c5ab9113b
  pullPolicy: Always
