replicaCount: 1
image:
  repository: quay.io/ortelius/ms-textfile-crud
  tag: main-v10.0.18-g255e1c
  sha: sha256:e47026c03485ccc2cacd67af7776d94c23c30fef1596e03af28fcce84ace2dd6
  pullPolicy: Always
